export const INIT_SELECTED_TAGS = 'INIT_SELECTED_TAGS';
export const INIT_TAGS = 'INIT_TAGS';
export const TOGGLE_TAG = 'TOGGLE_TAG';
export const UPDATE_CURRENT_FOLDER_ID = 'UPDATE_CURRENT_FOLDER_ID';
